### ISSUE TITLE
commands with subcommands not displayed correctly

### ISSUE THREAD

**Issue by Lemente** [appgurueu/cmdlib#2]
here is the issue with the mod [playerfaction](https://github.com/mt-mods/playerfactions)
![image](https://user-images.githubusercontent.com/27686967/202863828-3d801f80-b81e-45f5-aaf9-2a5bad5b8a0d.png)

**Comment by appgurueu** [comment]
:thinking: I remember fixing such a bug. Will get to this after the game jam ends.

**Comment by appgurueu** [comment]
Indeed, https://github.com/appgurueu/cmdlib/commit/eb42f89e69e1593b258b7b1686293582337a5a8f should have fixed this, but it seems the mod uses *`params`* rather than *`description`* for its description (ugh). Fixed in https://github.com/appgurueu/cmdlib/commit/fe44650a0018bfc3a2c6d2e711ced6c66c7fb771.
